import React from 'react';
import {Box, Typography} from '@material-ui/core';

export default function PrivacyPolicy() {

    return(
        // <Box>
        //     <Typography>Privacy Policy</Typography>
        // </Box>
        <section className="header">
        <h1>Privacy Policy</h1>
       
       
        <div className="container-fluid mt-3 border-top">
          <div className="row">
            <div className="col">
           
             <h1 className="heading-first m-3">
               Privacy Policy
             </h1>
           
             <p className="para m-3">
             Effective date: December 06, 2019
       
       
              </p>
              <p className="para m-3">
           Smart Parts Export ("us", "we", or "our") operates the http://smartpartsexport.com/ website (hereinafter referred to as the "Service").
            </p>
       
           <p className="para m-3">
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
           </p>
             <p className="para m-3">
               We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from http://smartpartsexport.com/
               </p>
       
            </div>
          </div>
        </div>
       
       
        <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
               Defination
             </h1>
       
             <div className="row">
             <h3 className="heading-secondary m-3">Service</h3>
              <p className="para para-second">Service is the http://smartpartsexport.com/ website operated by Smart Parts Export</p>
       
              <h3 className="heading-secondary m-3">Personal Data</h3>
             <p className="para para-second">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
       
       
             <h3 className="heading-secondary m-3">Usage Data</h3>
              <p className="para para-second">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
       
             <h3 className="heading-secondary m-3">Cookies</h3>
              <p className="para para-second">Cookies are small files stored on your device (computer or mobile device).</p>
             </div>
       
       
       
       
          </div>
       
       
       
            
        </div>
       
       
       
        <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Information Collection and Use
       
             </h1>
             <p className="para m-3">
             We collect several different types of information for various purposes to provide and improve our Service to you.
              </p>
       </div>
       </div>
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
         Types Of Data Collected
       
             </h1>
             <h1 className="para m-3">
               <b>Personal Data</b>
              </h1>
              <p className="para m-3">
              While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </p>
       
              <ul className="unordered mr-3">
                <li>Email Address</li>
                <li>First Name & Last Name</li>
                <li>Phone Number</li>
                <li>Cookies and Usage Data</li>
              </ul>
       </div>
       </div>
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
       Usage Data
       
             </h1>
             
              <p className="para m-3">
              We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
       
       
              </p>
       </div>
       </div>
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
       Tracking Cookies Data
       
             </h1>
             
              <p className="para m-3">
              We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
              </p>
       
              
              <p className="para m-3">
              Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
              </p>
              <p className="para m-3">
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </p>
       
       
              <p className="para m-3">
                Example of Cookies We use:
                <ul className="uno">
                  <li><b>Session Cookies</b>We use Session Cookies to operate our Service.</li>
                  <li><b>Preference Cookies</b>We use Preference Cookies to remember your preferences and various settings.</li>
                  <li><b>Security Cookies</b>We use Security Cookies for security purposes.</li>
                </ul>
              </p>
       </div>
       </div>
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
       Use of Data
       
             </h1>
             
             <ul className="unordered mr-3">
                <li>To provide and maintain the Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide analysis or valuable information so that we can improve the Service</li>
                <li>To monitor the usage of the Service</li>
                <li>To detect, prevent and address technical issues</li>
              </ul>
           
       </div>
       </div>
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Transfer Of Data
       
             </h1>
             
             <p className="para m-3">
             Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
       
       
              </p>
              <p className="para m-3">
              If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
       
       
              </p>
           
       
              <p className="para m-3">
              Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
       
       
              </p>
       
              <p className="para m-3">
       
              Smart Parts Export will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
              </p>
       
       
       </div>
       </div>
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Disclosure Of Data
       
       
             </h1>
             
             <p className="para m-3">
             Legal Requirements
       
       
       
              </p>
              <p className="para m-3">
              Smart Parts Export may disclose your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="unordered mr-3">
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Smart Parts Export
       </li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service
       </li>
                <li>To protect the personal safety of users of the Service or the public
       </li>
                <li>To protect against legal liability
       </li>
               
              </ul>
              <p className="para m-3">
              As an European citizen, under GDPR, you have certain individual rights. You can learn more about these guides in the GDPR Guide.
       
       
              </p>
       
       </div>
       </div>
       
       
       
       
       
       
       
       
       
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Security of Data
       
             </h1>
             
             <p className="para m-3">
             The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
       
       
       
              </p>
           
       </div>
       </div>
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Service Providers
       
       
             </h1>
             
             <p className="para m-3">
             We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
       
              </p>
       
              <p className="para m-3">
              These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
       
       
              </p>
           
       </div>
       </div>
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Analytics
       
       
       
             </h1>
             
             <p className="para m-3">
             We may use third-party Service Providers to monitor and analyze the use of our Service.
       
       
              </p>
              <p className="bold m-3"> <b>Piwik / Matomo
       
       </b></p>
              <p className="para m-3">
              Piwik or Matomo is a web analytics service. You can visit their Privacy Policy page here: https://matomo.org/privacy-policy
       
          
       
              </p>
              <p className="bold m-3"> <b>Clicky</b></p>
              <p className="para m-3">
              Clicky is a web analytics service. Read the Privacy Policy for Clicky here: https://clicky.com/terms
       
              
       
       
              </p>
             <p className="bold m-3"> <b>Statcounter</b></p>
              <p className="para m-3">
       
              Statcounter is a web traffic analysis tool. You can read the Privacy Policy for Statcounter here: https://statcounter.com/about/legal/
       
       
       
       
              </p>
       
              <p className="para m-3">
              Statcounter is a web traffic analysis tool. You can read the Privacy Policy for Statcounter here: https://statcounter.com/about/legal/
       
       
       
              </p>
       
       </div>
       </div>
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Links to Other Sites
       
       
       
             </h1>
             
             <p className="para m-3">
             Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
       
       
              </p>
       
              <p className="para m-3">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
       
       
       
              </p>
           
       </div>
       </div>
       
       
       
       
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Children's Privacys
       
       
       
       
             </h1>
             
             <p className="para m-3">
             Our Service does not address anyone under the age of 18 ("Children").
       
       
       
              </p>
       
              <p className="para m-3">
              We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
       
       
       
       
              </p>
           
       </div>
       </div>
       
       
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Changes to This Privacy Policy
       
       
       
       
       
             </h1>
             
             <p className="para m-3">
             We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
       
       
       
       
              </p>
       
              <p className="para m-3">
       
              We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
       
       
       
       
              </p>
       
              <p className="para m-3">
       
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
       
       
       
       
       
       </p>
           
       </div>
       </div>
       
       
       
       
       
       <div className="row">
          <div className="col">
          <h1 className="heading-first m-3">
          Contact Us
       
       
       
       
             </h1>
             
             <p className="para m-3">
             If you have any questions about this Privacy Policy, please contact us:
       
       
       
       
              </p>
       
              <p className="para m-3">
              <p><b>By email:</b>smartparts07@gmail.com</p>
              <p><b>By visiting this page on our website:</b> http://smartpartsexport.com/contact.php</p>
              <p><b>By phone number:</b>+91-8826477077</p>
       
       
       
       
       
              </p>
           
       </div>
       </div>
       </section>
       
        )


}