import React from 'react';
 import {Box, Typography} from '@material-ui/core';

export default function PrivacyPolicy() {

    return(
        // <Box>
        //     <Typography>Privacy Policy</Typography>
        // </Box>
        <Box style={{marginTop: "65px"}}>

        <Typography variant="h1">Privacy Policy</Typography>
       
       
        <Box >
          <Box >
            <Box >
           
             <Typography variant="h1" >
               Privacy Policy
             </Typography>
           
             <Typography variant="body1" >
             Effective date: December 06, 2019
       
       
              </Typography>
              <Typography variant="body1" >
           Smart Parts Export ("us", "we", or "our") operates the http://smartpartsexport.com/ website (hereinafter referred to as the "Service").
            </Typography>
       
           <Typography variant="body1">
            This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
           </Typography>
             <Typography variant="body1" >
               We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from http://smartpartsexport.com/
               </Typography>
       
            </Box>
          </Box>
        </Box>
       
       
        <Box >
          <Box >
          <Typography variant="h1" >
               Defination
             </Typography>
       
             <Box >
             <Typography variant="h3" >Service</Typography>
              <Typography variant="body1" >Service is the http://smartpartsexport.com/ website operated by Smart Parts Export</Typography>
       
              <Typography variant="h3" >Personal Data</Typography>
             <Typography variant="body1" >Personal Data means data about a living inBoxidual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</Typography>
       
       
             <Typography variant="h3" >Usage Data</Typography>
              <Typography variant="body1" >Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</Typography>
       
             <Typography variant="h3" >Cookies</Typography>
              <Typography variant="body1" >Cookies are small files stored on your device (computer or mobile device).</Typography>
             </Box>
       
       
       
       
          </Box>
       
       
       
            
        </Box>
       
       
       
        <Box >
          <Box >
          <Typography variant="h1" >
          Information Collection and Use
       
             </Typography>
             <Typography variant="h1" >
             We collect several different types of information for various purposes to provide and improve our Service to you.
              </Typography>
       </Box>
       </Box>
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
         Types Of Data Collected
       
             </Typography>
             <Typography variant="h1" >
               <b>Personal Data</b>
              </Typography>
              <Typography variant="body1" >
              While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
              </Typography>
       
              <ul >
                <li>Email Address</li>
                <li>First Name & Last Name</li>
                <li>Phone Number</li>
                <li>Cookies and Usage Data</li>
              </ul>
       </Box>
       </Box>
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
       Usage Data
       
             </Typography>
             
              <Typography variant="body1" >
              We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
       
       
              </Typography>
       </Box>
       </Box>
       
       <Box >
          <Box >
          <Typography variant="h1" >
       Tracking Cookies Data
       
             </Typography>
             
              <Typography variant="body1" >
              We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
              </Typography>
       
              
              <Typography variant="body1" >
              Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.
              </Typography>
              <Typography variant="body1" >
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
              </Typography>
       
       
              <Typography variant="body1" >
                Example of Cookies We use:
                <ul >
                  <li><b>Session Cookies</b>We use Session Cookies to operate our Service.</li>
                  <li><b>Preference Cookies</b>We use Preference Cookies to remember your preferences and various settings.</li>
                  <li><b>Security Cookies</b>We use Security Cookies for security purposes.</li>
                </ul>
              </Typography>
       </Box>
       </Box>
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
       Use of Data
       
             </Typography>
             
             <ul >
                <li>To provide and maintain the Service</li>
                <li>To notify you about changes to our Service</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                <li>To provide analysis or valuable information so that we can improve the Service</li>
                <li>To monitor the usage of the Service</li>
                <li>To detect, prevent and address technical issues</li>
              </ul>
           
       </Box>
       </Box>
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Transfer Of Data
       
             </Typography>
             
             <Typography variant="body1" >
             Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
       
       
              </Typography>
              <Typography variant="body1" >
              If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.
       
       
              </Typography>
           
       
              <Typography variant="body1" >
              Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
       
       
              </Typography>
       
              <Typography variant="body1" >
       
              Smart Parts Export will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
              </Typography>
       
       
       </Box>
       </Box>
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Disclosure Of Data
       
       
             </Typography>
             
             <Typography variant="body1" >
             Legal Requirements
       
       
       
              </Typography>
              <Typography variant="body1" >
              Smart Parts Export may disclose your Personal Data in the good faith belief that such action is necessary to:
              </Typography>
              <ul >
                <li>To comply with a legal obligation</li>
                <li>To protect and defend the rights or property of Smart Parts Export
       </li>
                <li>To prevent or investigate possible wrongdoing in connection with the Service
       </li>
                <li>To protect the personal safety of users of the Service or the public
       </li>
                <li>To protect against legal liability
       </li>
               
              </ul>
              <Typography variant="body1" >
              As an European citizen, under GDPR, you have certain inBoxidual rights. You can learn more about these guides in the GDPR Guide.
       
       
              </Typography>
       
       </Box>
       </Box>
       
       
       
       
       
       
       
       
       
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Security of Data
       
             </Typography>
             
             <Typography variant="body1" >
             The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
       
       
       
              </Typography>
           
       </Box>
       </Box>
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Service Providers
       
       
             </Typography>
             
             <Typography variant="body1" >
             We may employ third party companies and inBoxiduals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
       
              </Typography>
       
              <Typography variant="body1" >
              These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
       
       
              </Typography>
           
       </Box>
       </Box>
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Analytics
       
       
       
             </Typography>
             
             <Typography variant="body1" >
             We may use third-party Service Providers to monitor and analyze the use of our Service.
       
       
              </Typography>
              <Typography variant="body1" > <b>Piwik / Matomo
       
       </b></Typography>
              <Typography variant="body1" >
              Piwik or Matomo is a web analytics service. You can visit their Privacy Policy page here: https://matomo.org/privacy-policy
       
          
       
              </Typography>
              <Typography variant="body1" > <b>Clicky</b></Typography>
              <Typography variant="body1">
              Clicky is a web analytics service. Read the Privacy Policy for Clicky here: https://clicky.com/terms
       
              
       
       
              </Typography>
             <Typography variant="body1" > <b>Statcounter</b></Typography>
              <Typography variant="body1" >
       
              Statcounter is a web traffic analysis tool. You can read the Privacy Policy for Statcounter here: https://statcounter.com/about/legal/
       
       
       
       
              </Typography>
       
              <Typography variant="body1" >
              Statcounter is a web traffic analysis tool. You can read the Privacy Policy for Statcounter here: https://statcounter.com/about/legal/
       
       
       
              </Typography>
       
       </Box>
       </Box>
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Links to Other Sites
       
       
       
             </Typography>
             
             <Typography variant="body1" >
             Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
       
       
              </Typography>
       
              <Typography variant="body1" >
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
       
       
       
              </Typography>
           
       </Box>
       </Box>
       
       
       
       
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Children's Privacys
       
       
       
       
             </Typography>
             
             <Typography variant="body1" >
             Our Service does not address anyone under the age of 18 ("Children").
       
       
       
              </Typography>
       
              <Typography variant="body1" >
              We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
       
       
       
       
              </Typography>
           
       </Box>
       </Box>
       
       
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Changes to This Privacy Policy
       
       
       
       
       
             </Typography>
             
             <Typography variant="body1" >
             We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
       
       
       
       
              </Typography>
       
              <Typography variant="body1" >
       
              We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
       
       
       
       
              </Typography>
       
              <Typography variant="body1" >
       
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
       
       
       
       
       
       </Typography>
           
       </Box>
       </Box>
       
       
       
       
       
       <Box >
          <Box >
          <Typography variant="h1" >
          Contact Us
       
       
       
       
             </Typography>
             
             <Typography variant="body1" >
             If you have any questions about this Privacy Policy, please contact us:
       
       
       
       
              </Typography>
       
              <Typography variant="body1" >
              <Typography variant="body1"><b>By email:</b>smartparts07@gmail.com</Typography>
              <Typography variant="body1"><b>By visiting this page on our website:</b> http://smartpartsexport.com/contact.php</Typography>
              <Typography variant="body1"><b>By phone number:</b>+91-8826477077</Typography>
       
       
       
       
       
              </Typography>
           
       </Box>
       </Box>
       
       </Box>
        )


}